### ISSUE TITLE
Cannot build with keycloak 26.4.7

### ISSUE THREAD

**Issue by cdevienne** [mabartos/keycloak-authn-policies#2]
I tried to rebuild keycloak 26.4.7 with the js folder of keycloak-authn-policies merged in keycloak 'js'.

The build fails with the logs below, which seems to indicate that some changes in keycloak are not compatible with keycloak-authn-policies.
What is the most recent version of keycloak that is supposed to work ?

```
[INFO] ❌ [apps/admin-ui:build] exited with exit code 2. Output:
[INFO] ❌ [apps/admin-ui:build] exited with exit code 2. Output:vite v7.1.6 building for production...
[INFO] transforming...
[INFO] ✓ 2595 modules transformed.
[INFO] src/authentication/AuthenticationPolicyDetails.tsx(24,27): error TS2307: Cannot find module '../components/alert/Alerts' or its corresponding type declarations.
[INFO] 
[INFO] src/authentication/AuthenticationPolicyDetails.tsx(28,26): error TS2307: Cannot find module '../utils/useFetch' or its corresponding type declarations.
[INFO] src/authentication/AuthenticationPolicyDetails.tsx(120,11): error TS7031: Binding element 'policy' implicitly has an 'any' type.
[INFO] src/authentication/AuthenticationPolicyDetails.tsx(120,19): error TS7031: Binding element 'executions' implicitly has an 'any' type.
[INFO] src/authentication/AuthenticationPolicyDetails.tsx(120,31): error TS7031: Binding element 'configMap' implicitly has an 'any' type.
[INFO] src/authentication/AuthenticationSection.tsx(19,27): error TS2307: Cannot find module '../components/alert/Alerts' or its corresponding type declarations.
[INFO] src/authentication/AuthenticationSection.tsx(21,33): error TS2307: Cannot find module '../components/keycloak-spinner/KeycloakSpinner' or its corresponding type declarations.
[INFO] src/authentication/AuthenticationSection.tsx(22,32): error TS2307: Cannot find module '../components/list-empty-state/ListEmptyState' or its corresponding type declarations.
[INFO] ❌ 1 script failed.
[INFO] ❌ 1 script failed.src/authentication/AuthenticationSection.tsx(27,35): error TS2307: Cannot find module '../components/table-toolbar/KeycloakDataTable' or its corresponding type declarations.
[INFO] src/authentication/AuthenticationSection.tsx(255,34): error TS7031: Binding element 'data' implicitly has an 'any' type.
[INFO] src/authentication/AuthenticationSection.tsx(290,34): error TS7006: Parameter 'row' implicitly has an 'any' type.
[INFO] src/authentication/AuthenticationSection.tsx(295,34): error TS7006: Parameter 'row' implicitly has an 'any' type.
[INFO] src/authentication/EmptyAuthenticationPolicy.tsx(13,30): error TS2307: Cannot find module '../components/list-empty-state/ListEmptyState' or its corresponding type declarations.
[INFO] src/authentication/components/AddPolicyFlowDropdown.tsx(12,26): error TS2307: Cannot find module '../../utils/useFetch' or its corresponding type declarations.
[INFO] src/authentication/components/AddPolicyFlowDropdown.tsx(42,12): error TS7031: Binding element 'providerId' implicitly has an 'any' type.
[INFO] src/authentication/form/CreateAuthenticationPolicy.tsx(8,25): error TS2307: Cannot find module '../../components/alert/Alerts' or its corresponding type declarations.
[INFO] src/workflows/CreateWorkflow.tsx(55,25): error TS2339: Property 'workflows' does not exist on type 'KeycloakAdminClient'.
[INFO] src/workflows/WorkflowsSection.tsx(44,41): error TS2339: Property 'workflows' does not exist on type 'KeycloakAdminClient'.
[INFO] src/workflows/WorkflowsSection.tsx(63,27): error TS2339: Property 'workflows' does not exist on type 'KeycloakAdminClient'.
[INFO]  ELIFECYCLE  Command failed with exit code 1.
```

**Comment by mabartos** [comment]
@cdevienne Thanks for creating this issue! As this project is only a Proof of Concept, there has not been any recent work done on this. That means that the code might be inconsistent with the latest KC releases.
